import React from 'react';
import { useEffect, useState } from 'react';
import DOMPurify from 'isomorphic-dompurify';
import { marked } from 'marked';

import { DynamicUiComponentProps, DynamicUiFormFieldRef } from '../DynamicUi';
import { classNames } from '../../../utils/classNames';

export function ParagraphFormField(
  { formField: { defaultValue, label } }: DynamicUiComponentProps,
  ref: DynamicUiFormFieldRef,
) {
  const [generatedHtml, setGeneratedHtml] = useState('');
  useEffect(() => {
    const html = marked.parse(defaultValue?.toString() ?? label?.toString() ?? '', {
      renderer: new MarkdownRenderer(),
      hooks: {
        postprocess: (html) => DOMPurify.sanitize(html, { ADD_ATTR: ['target'] }),
        preprocess: marked.Hooks.prototype.preprocess,
      },
    });

    setGeneratedHtml(html);
  }, [defaultValue, label]);

  return (
    <div
      /** Style the HTML Elements generated by marked */
      className={classNames(
        // base
        'dynamic-ui-text-sm',
        // paragraph elements
        '[&_p]:dynamic-ui-my-4 first-of-type:[&_p]:dynamic-ui-mb-4 first-of-type:[&_p]:dynamic-ui-mt-0',
        // links/anchor
        '[&_a]:dynamic-ui-text-[color:var(--dui-link-color)] [&_a]:dynamic-ui-underline hover:[&_a]:dynamic-ui-text-[color:var(--dui-link-hover-color)]',
        // headings
        '[&_h1]:dynamic-ui-text-2xl [&_h1]:dynamic-ui-font-bold [&_h2]:dynamic-ui-text-xl [&_h2]:dynamic-ui-font-bold [&_h3]:dynamic-ui-text-lg [&_h3]:dynamic-ui-font-bold [&_h4]:dynamic-ui-text-base [&_h4]:dynamic-ui-font-bold [&_h5]:dynamic-ui-text-sm [&_h5]:dynamic-ui-font-bold [&_h6]:dynamic-ui-text-xs [&_h6]:dynamic-ui-font-bold',
        // code blocks
        '[&_code]:dynamic-ui-text-[#e83e8c] [&_pre]:dynamic-ui-my-4 [&_pre]:dynamic-ui-bg-gray-100 [&_pre]:dark:dynamic-ui-bg-dynamicui-gray-700 [&_pre_code]:dynamic-ui-text-inherit',
        // revert margin
        '[&_blockquote]:dynamic-ui-m-[revert] [&_fieldset]:dynamic-ui-m-[revert] [&_h1]:dynamic-ui-m-[revert] [&_h2]:dynamic-ui-m-[revert] [&_h3]:dynamic-ui-m-[revert] [&_h4]:dynamic-ui-m-[revert] [&_h5]:dynamic-ui-m-[revert] [&_h6]:dynamic-ui-m-[revert] [&_menu]:dynamic-ui-m-[revert] [&_ol]:dynamic-ui-m-[revert] [&_ul]:dynamic-ui-m-[revert]',
        // revert padding
        '[&_fieldset]:dynamic-ui-p-[revert] [&_menu]:dynamic-ui-p-[revert] [&_ol]:dynamic-ui-p-[revert] [&_ul]:dynamic-ui-p-[revert]',
        // list styles
        '[&_ol]:dynamic-ui-list-decimal [&_ol_p]:dynamic-ui-my-2 first-of-type:[&_ol_p]:dynamic-ui-my-4 [&_ul]:dynamic-ui-list-disc [&_ul_p]:dynamic-ui-my-2 first-of-type:[&_ul_p]:dynamic-ui-my-4',
        // checkbox
        "[&_input[type='checkbox']]:dynamic-ui-border [&_input[type='checkbox']]:dynamic-ui-h-4 [&_input[type='checkbox']]:dynamic-ui-w-4 [&_input[type='checkbox']]:dynamic-ui-rounded [&_input[type='checkbox']]:dynamic-ui-border-[color:var(--dui-border-color)] [&_input[type='checkbox']]:dynamic-ui-text-sky-600 [&_input[type='checkbox']]:hover:dynamic-ui-border-[color:var(--dui-border-color)] [&_input[type='checkbox']]:dark:dynamic-ui-border-2 [&_input[type='checkbox']]:dark:dynamic-ui-border-solid [&_input[type='checkbox']]:dark:dynamic-ui-border-transparent [&_input[type='checkbox']]:dark:dynamic-ui-bg-dynamicui-gray-350 [&_input[type='checkbox']]:dark:dynamic-ui-text-[#007bff40] [&_input[type='checkbox']]:dark:hover:dynamic-ui-border-transparent [&_input[type='checkbox']]:dark:hover:checked:dynamic-ui-bg-dynamicui-gray-350",
      )}
      dangerouslySetInnerHTML={{ __html: generatedHtml }}
    ></div>
  );
}

class MarkdownRenderer extends marked.Renderer {
  link(href: string, title: string | null | undefined, text: string): string {
    const link = super.link(href, title, text);

    return link.replace('<a', "<a target='_blank'");
  }

  html(html: string, block?: boolean | undefined): string {
    const result = super.html(html, block);

    if (result.startsWith('<a ') && !result.includes('target=')) {
      return result.replace('<a ', `<a target="_blank" `);
    }

    return result;
  }
}
