import React from 'react';
import { useEffect, useState } from 'react';
import DOMPurify from 'isomorphic-dompurify';
import { marked } from 'marked';

import type { DataModels } from '@5minds/processcube_engine_sdk';

import { DynamicUiFormFieldRef } from '../DynamicUi';
import { classNames } from '../../../utils/classNames';

type ParagraphFormFieldProps = {
  formField: DataModels.FlowNodeInstances.UserTaskFormField;
};

export function ParagraphFormField(
  { formField: { defaultValue, label } }: ParagraphFormFieldProps,
  ref: DynamicUiFormFieldRef,
) {
  const [generatedHtml, setGeneratedHtml] = useState('');
  useEffect(() => {
    const html = marked.parse(defaultValue?.toString() ?? label?.toString() ?? '', {
      renderer: new MarkdownRenderer(),
      hooks: {
        postprocess: (html) => DOMPurify.sanitize(html, { ADD_ATTR: ['target'] }),
        preprocess: marked.Hooks.prototype.preprocess,
      },
    });

    setGeneratedHtml(html);
  }, [defaultValue, label]);

  return (
    <div
      /** Style the HTML Elements generated by marked */
      className={classNames(
        // base
        'text-sm',
        // paragraph elements
        '[&_p]:my-4 first-of-type:[&_p]:mb-4 first-of-type:[&_p]:mt-0',
        // links/anchor
        '[&_a]:text-[color:var(--uic-link-color)] [&_a]:underline hover:[&_a]:text-[color:var(--uic-link-hover-color)]',
        // headings
        '[&_h1]:text-2xl [&_h1]:font-bold [&_h2]:text-xl [&_h2]:font-bold [&_h3]:text-lg [&_h3]:font-bold [&_h4]:text-base [&_h4]:font-bold [&_h5]:text-sm [&_h5]:font-bold [&_h6]:text-xs [&_h6]:font-bold',
        // code blocks
        '[&_pre]:dark:bg-dynamicui-gray-700 [&_code]:text-[#e83e8c] [&_pre]:my-4 [&_pre]:bg-gray-100 [&_pre_code]:text-inherit',
        // revert margin
        '[&_blockquote]:m-[revert] [&_fieldset]:m-[revert] [&_h1]:m-[revert] [&_h2]:m-[revert] [&_h3]:m-[revert] [&_h4]:m-[revert] [&_h5]:m-[revert] [&_h6]:m-[revert] [&_menu]:m-[revert] [&_ol]:m-[revert] [&_ul]:m-[revert]',
        // revert padding
        '[&_fieldset]:p-[revert] [&_menu]:p-[revert] [&_ol]:p-[revert] [&_ul]:p-[revert]',
        // list styles
        '[&_ol]:list-decimal [&_ol_p]:my-2 first-of-type:[&_ol_p]:my-4 [&_ul]:list-disc [&_ul_p]:my-2 first-of-type:[&_ul_p]:my-4',
        // checkbox
        "[&_input[type='checkbox']]:dark:bg-dynamicui-gray-350 [&_input[type='checkbox']]:dark:hover:checked:bg-dynamicui-gray-350 [&_input[type='checkbox']]:h-4 [&_input[type='checkbox']]:w-4 [&_input[type='checkbox']]:rounded [&_input[type='checkbox']]:border-[color:var(--uic-border-color)] [&_input[type='checkbox']]:text-sky-600 [&_input[type='checkbox']]:hover:border-[color:var(--uic-border-color)] [&_input[type='checkbox']]:dark:border-2 [&_input[type='checkbox']]:dark:border-solid [&_input[type='checkbox']]:dark:border-transparent [&_input[type='checkbox']]:dark:text-[#007bff40] [&_input[type='checkbox']]:dark:hover:border-transparent",
      )}
      dangerouslySetInnerHTML={{ __html: generatedHtml }}
    ></div>
  );
}

class MarkdownRenderer extends marked.Renderer {
  link(href: string, title: string | null | undefined, text: string): string {
    const link = super.link(href, title, text);

    return link.replace('<a', "<a target='_blank'");
  }

  html(html: string, block?: boolean | undefined): string {
    const result = super.html(html, block);

    if (result.startsWith('<a ') && !result.includes('target=')) {
      return result.replace('<a ', `<a target="_blank" `);
    }

    return result;
  }
}
